### ISSUE TITLE
Drive check crashes (check plugin version 1.2)

### ISSUE THREAD

**Issue by sploenix** [Yogibaer75/Check_MK-Things#10] opened 2022-06-22 07:05 UTC
Exception:

TypeError (int() argument must be a string, a bytes-like object or a number, not 'NoneType')

Problematic field:

File "/omd/sites/SITEXYZ/local/lib/python3/cmk/base/plugins/agent_based/dell_idrac_rf_drives.py", line 55, in check_dell_idrac_rf_drives
    int(data.get("PredictedMediaLifeLeftPercent", 0))

Value of the field:

'PredictedMediaLifeLeftPercent': None,

Kind regards
Sören

**Comment by Yogibaer75** [comment] 2022-06-22 07:27
That's strange, in your data it looks like that key is present but without a value.
Is it possible that you can sent me the agent output of such a system?

best regards
Andreas

**Comment by sploenix** [comment] 2022-06-22 07:39
The key is present and it's value is None, which is neither a string, a bytes like object or a number, but of NoneType. So surrounding the conversion with a try except and setting to 0 if the conversion failed should probably work.
Sending the whole agent output is not possible atm.

Sören

**Comment by Yogibaer75** [comment] 2022-06-22 08:54
The problem is that this value should not be "None" if you have an SSD.
That normally means it is a software bug in the iDRAC firmware.

I can only implement a work around where i generate a warning that the value is missing on the SSD.

**Comment by sploenix** [comment] 2022-06-22 09:08
Even if this is a bug in iDRAC firmware, there's not much I can do about it. This is a recent system with the most recent firmware. 

Generating a warning would be one possibility, but this would bloat our problem view in check_mk. From a technical perspective, I share your opinion, but from our use case, we don't bother if this value is missing and would prefer not get a warning. :)

**Comment by Yogibaer75** [comment] 2022-06-22 18:06
Only as information for myself. Is the drive a normal SSD or NVMe?
It is possible that this value only exists for NVMe drives.
What would be nice is the agent output for one single of these SSD drives. Not the complete agent output :)

I will first make an fix that it not crashes.

**Comment by Yogibaer75** [comment] 2022-06-22 18:22
Hopefully fixed with Commit https://github.com/Yogibaer75/Check_MK-Things/commit/a41b7ab0f67182df449851086481d4a3ddc16b56

**Closed as completed by Yogibaer75** 2022-06-22 18:22 UTC
