### ISSUE TITLE
Issue in CheckMK Patch Day Plugin when processing regex

### ISSUE THREAD

**Issue by DirkHoelscherKH** [Yogibaer75/Check_MK-Things#72] opened 2024-08-20 10:41 UTC
If I exclude some "unwanted updates" in the agent rules of CheckMK plugin "Windows Patch Day”, the regex expression does not work as expected.
If the exclude is
![image](https://github.com/user-attachments/assets/734fe78a-f189-4054-af86-428da4b9b03b)
(to exclude updates with the shown KB-numbers) it don't exclude these updates in the agent output. The $filter_regex in windows_patch_day.ps1 has the value
(?i)^(KB2267602|KB4052623)
so it looks right.

If the exclude in agent rule is
![image](https://github.com/user-attachments/assets/449c4a74-0a5d-4c6b-b367-e064557ba3df)
the content of $filter_regex will be escaped as
![image](https://github.com/user-attachments/assets/e07f7d08-2c24-425e-8d45-c86dccec6fe0)
This completely destroys the regex expression.

Used version is 2.3.1 on Checkmk Enterprise Edition 2.3.0p12

Is this a bug or how exactly are the unwanted updates has to be defined?

**Comment by Yogibaer75** [comment] 2024-08-25 09:52
Ok then i need to modify the description for the input field to "infix" and not a complete regex.
A complete regex here makes no sense as the Powershell plugin already defines the regex.
`[regex] $filter_regex ='(?i)^(' + (($filterstring |ForEach-Object {[regex]::escape($_)}) -join "|") + ')'`

**Comment by DirkHoelscherKH** [comment] 2024-08-26 06:09
Thank you. That sounds like a solution.

But how can updates be specified that should not be taken into account by the plugin (e.g. the Defender's multiple daily updates)? If a KB number is entered for each field (see first post), these updates are not filtered out.

**Comment by Yogibaer75** [comment] 2024-08-26 07:32
The problem is with 2.3 API i cannot prefill the fields with some values like in 2.2.
Here is a screenshot from 2.2 values - this should also work in 2.3.
You don't need to use the KB number also the name of the ignored update is possible.
<img width="419" alt="image" src="https://github.com/user-attachments/assets/1f3c20a4-6188-4e06-9246-ddd93adb07d4">

**Comment by DirkHoelscherKH** [comment] 2024-08-26 08:52
Thanks. The exclusions work with the single names of the updates.

**Comment by DirkHoelscherKH** [comment] 2024-08-26 09:09
A small suggestion for improvement: if the update insall-histroy is empty (because no updates have been installed or all updates are filtered out by regex), the service displays “Item not found in monitoring data” because the agent output is empty
It would be nice if this message were intercepted, as otherwise the service will be displayed as “vanished” the next time dicsovery is run. Thank you.

![image](https://github.com/user-attachments/assets/00bc3cab-d231-4954-9e9f-18e9a5506741)

**Comment by Yogibaer75** [comment] 2024-09-02 07:17
The problem for the empty output is not so easy to solve.
There are two possible reasons.
- installed patch like 23H2 or similar --> result empty list of updates also without filter
- set filter like in your example an nothing else is installed

What i can fix is the "Item not found" at check time. The discovery is not so easy to change as empty data means no section and in result no service is found.
I would recommend if this is a problem to set this as enforced service.

**Comment by Yogibaer75** [comment] 2024-09-16 18:54
Uploaded new version that should fix the UNKN problem. 2907704
The vanished service problem will be fixed the next days. I have an idea how to do this.

**Comment by Yogibaer75** [comment] 2024-09-22 20:27
With commit f3b89f6 also the vanished service problem should be fixed.
I also changed the text for the rule to exclude updates to an prefix match from regex.

**Closed as completed by Yogibaer75** 2024-09-22 20:27 UTC
