### ISSUE TITLE
Dell PowerVault ME4 CheckMK 2.0: wrong Python version

### ISSUE THREAD

**Issue by mbunkus** [Yogibaer75/Check_MK-Things#4] opened 2021-07-13 15:52 UTC
In the [special agent](https://github.com/Yogibaer75/Check_MK-Things/blob/master/check%20plugins%202.0/dell_powervault_me4/agents/special/agent_dellpowervault#L1) the shebang is still referring to an unversioned Python executable instead of `python3`. This leads to problems on systems where `python` is indeed Python 2, such as Ubuntu 20.04.

**Comment by Yogibaer75** [comment] 2021-07-14 06:40
Should be now fixed with https://github.com/Yogibaer75/Check_MK-Things/commit/3bdcd2449cbe4e6c178c281f9b705f7e36cad2a9
This was not seen at migration time as the migration was only be done with an existing agent output.

**Closed as completed** 2021-07-14 06:40 UTC

**Comment by mbunkus** [comment] 2021-07-14 07:02
Thank you very much.

**Comment by d3sh0m3d** [comment] 2022-08-02 08:21
Tested it with version 2.0.0p23 and got some error from agent 

Agent exited with code 1: Traceback (most recent call last):
File "/omd/sites/***/lib/python3/urllib3/connection.py", line 174, in _new_conn
conn = connection.create_connection(
File "/omd/sites/***/lib/python3/urllib3/util/connection.py", line 96, in create_connection
raise err
File "/omd/sites/***/lib/python3/urllib3/util/connection.py", line 86, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/omd/sites/***/lib/python3/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/omd/sites/***/lib/python3/urllib3/connectionpool.py", line 382, in _make_request
self._validate_conn(conn)
File "/omd/sites/***/lib/python3/urllib3/connectionpool.py", line 1010, in _validate_conn
conn.connect()
File "/omd/sites/***/lib/python3/urllib3/connection.py", line 358, in connect
conn = self._new_conn()
File "/omd/sites/***/lib/python3/urllib3/connection.py", line 186, in _new_conn
raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe1c288bd90>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/omd/sites/***/lib/python3/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/omd/sites/***/lib/python3/urllib3/connectionpool.py", line 755, in urlopen
retries = retries.increment(
File "/omd/sites/***/lib/python3/urllib3/util/retry.py", line 574, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.141.110.248', port=443): Max retries exceeded with url: /api/login/d29449d95069cce7e53bca8bfe47b12f1503c954f54365ce5a12950d6b14416e (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe1c288bd90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/omd/sites/***/local/share/check_mk/agents/special/agent_dellpowervault", line 67, in <module>
sys.exit(main())
File "/omd/sites/***/local/share/check_mk/agents/special/agent_dellpowervault", line 53, in main
r = s.get(url + "/api/login/" + auth_string, verify=False)
File "/omd/sites/***/lib/python3/requests/sessions.py", line 555, in get
return self.request('GET', url, **kwargs)
File "/omd/sites/***/lib/python3/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/omd/sites/***/lib/python3/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/omd/sites/***/lib/python3/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='10.141.110.248', port=443): Max retries exceeded with url: /api/login/d29449d95069cce7e53bca8bfe47b12f1503c954f54365ce5a12950d6b14416e (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe1c288bd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
